name: dsci401
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - pip
  - pip:
      - jupyterlab-quarto
      - ipykernel